- midnight.css
There are a few other elements changed by Discord.
> Updated custom title class in CSS

- midnight.css
https://user-images.githubusercontent.com/65787561/227799834-1e7bc0d0-b52e-45d7-a974-3738cb57f7ff.mp4
> Theme 'Channels & Roles'

- midnight.css
For each, the left or first image is the new, right or second image is last. These changes make elements like these look way more visible.
> General improvements for mostly embeds

- midnight.css
Added styles for Create/Join a server modal
this will fix refact0r/midnight-discord#14
> fixed create/join a server modals

- midnight.css
- midnight.theme.css
Added more rounded corners to the theme.
> ⭕ Added more rounded corners

- flavors/midnight-biscuit.theme.css
Biscuit colorscheme: https://github.com/Biscuit-Colorscheme/biscuit
> Add biscuit flavor

- midnight.css
Adds a `--streaming-indicator` value
> feat: streaming indicator

- midnight.css
themes active buttons with accent
> vencord spotify player buttons

- flavors/midnight-rose-pine.theme.css
I tried to get all the colors correctly as per the [default palette](https://rosepinetheme.com/palette/ingredients/)
> feat: rose pine theme

- flavors/midnight-amaryllis.theme.css
- flavors/midnight-biscuit.theme.css
- flavors/midnight-catppuccin-frappe.theme.css
- flavors/midnight-catppuccin-macchiato.theme.css
- flavors/midnight-catppuccin-mocha.theme.css
- flavors/midnight-night-owl.theme.css
- flavors/midnight-nocturne.theme.css
- flavors/midnight-nord.theme.css
- flavors/midnight-pichu.theme.css
- flavors/midnight-rose-pine.theme.css
- flavors/midnight-spotify.theme.css
- flavors/midnight-vencord.theme.css
- midnight.css
- Added coloring for spoilers.
- Improved look and feel of settings checkboxes.
- Tidied up theme files.
- Divider changes:
- New divider-thickness variable, default is 3px. (scales)
- Removed unnecessary padding for 'New' text.
- Bugs fixed:
- Bot tag checkmark coloring.
- Fullscreen VC chat spacing.
- Incorrect dnd color listed in theme files.
- Multiple discovery page fixes, including: spacing, color, and roundness.
- Incorrect default dnd color in theme files.
- Flickering on settings checkboxes.
> Bug fixes and improvements.

- midnight.css
- Added scroll compatibility to decor on the decoration picker page
> Decor compat added

- midnight.css
Changes:
- Added `--bg-2` to `--bg-mod-subtle`. Fixes things like poll vote answers, forum searchbar footer bg, etc.
- Various improvements to forum channels.
- Added missing backgrounds for some search boxes.
- Removed `.newChannel_ecb303` fix, I believe its no longer needed.
- Fixed server list buttons background color.
> Bug fixes and forum channel improvements

- midnight.css
> unread pill

- midnight.css
> hovered menu item arrow

- flavors/midnight-amaryllis.theme.css
- flavors/midnight-biscuit.theme.css
- flavors/midnight-catppuccin-frappe.theme.css
- flavors/midnight-catppuccin-macchiato.theme.css
- flavors/midnight-catppuccin-mocha.theme.css
- flavors/midnight-night-owl.theme.css
- flavors/midnight-nocturne.theme.css
- flavors/midnight-nord.theme.css
- flavors/midnight-pichu.theme.css
- flavors/midnight-rose-pine.theme.css
- flavors/midnight-spotify.theme.css
- flavors/midnight-test.theme.css
- flavors/midnight-test2.theme.css
- flavors/midnight-vencord.theme.css
- midnight.css
- midnight.theme.css
> Configurable nav button style (Styled / Windows)

- midnight.css
Fixes:
- Discovery Icons gradient (footer class was changed)
- That one weird corner which wasn't rounded
> Small patches

- midnight.css
Let the madness end
Fixes discovery gradient once again because class was changed
> They rerolled the footer class again

- flavors/midnight-amaryllis.theme.css
- flavors/midnight-biscuit.theme.css
- flavors/midnight-catppuccin-frappe.theme.css
- flavors/midnight-catppuccin-macchiato.theme.css
- flavors/midnight-catppuccin-mocha.theme.css
- flavors/midnight-pichu.theme.css
- flavors/midnight-rose-pine.theme.css
Update to newer icon class for custom DM icons (catpuccin etc)
> Update DM Icon classes

- midnight.css
i opened up the soundboard and found out the soundboard buttons weren't themed so i fixed it
> fix: soundboard buttons

- README.md
- themes/flavors/midnight-rose-pine-moon.theme.css
I really like the smoothness of the midnight theme, and I'm a fan of the Rose Pine Moon color scheme (I use it on pretty much anything possible), so I took the Rose Pine flavor and adjusted the colors with the Rose Pine Moon color palette. Thanks for the themes! 💖💖💖
EDIT: Forgot the image
> Add Rose Pine Moon flavor

- build/midnight.css
- src/colors.css
tiiiny PR because discord changed the colours of online, idle, and dnd slightly (again)
> Fix for new discord status colours

- build/midnight.css
- src/colors.css
> Fix crown color

- build/midnight.css
- src/colors.css
> Fix button colors in user settings
